apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::383585068161:role/projectx_cluster_ubuntu25b-workers-iam-role
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
        
#eks-node bootstrapper
# delete aws-auth cm 
# dont need this yaml applied (old)
# we should be able to bootstrap without it aws-auth.yaml
# try to apply system bootstrapper group in access entries
# if doesn't work run eks:node-bootstrapper  

# user_data = base64encode(<<-EOT
#     #!/bin/bash
#     set -o xtrace
#     /etc/eks/bootstrap.sh ${local.cluster_name} \
#       --apiserver-endpoint '${aws_eks_cluster.main_cluster.endpoint}' \
#       --b64-cluster-ca '${aws_eks_cluster.main_cluster.certificate_authority[0].data}' \
#       --kubelet-extra-args '--node-labels=node.kubernetes.io/lifecycle=normal' # add this as well
#   EOT
#   )

# need access entries not aws auth cm.